### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel" : "JUNIOR",
  "developSkillType" : "FRONT_END",
  "experienceYears" : 2,
  "memberId" : "kimhunsope",
  "name" : "mouse",
  "age" : 20
}